# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 08:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interviewid', models.IntegerField(primary_key=True, serialize=False)),
                ('interviewdate', models.DateField()),
                ('interviewstatus', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('jobid', models.IntegerField(primary_key=True, serialize=False)),
                ('jobdescription', models.CharField(blank=True, max_length=200, null=True)),
                ('jobstatus', models.CharField(max_length=200)),
                ('jobcreatedate', models.DateField(default=datetime.date(2019, 1, 21))),
                ('assignedto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('candidateemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to=b'documents/')),
                ('candidatename', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaddate', models.DateField(default=datetime.date(2019, 1, 21))),
                ('resumestatus', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('primaryskill', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorname', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='primaryskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.TechnicalSkills'),
        ),
        migrations.AddField(
            model_name='resume',
            name='submittedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='vendorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Vendor'),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidateemail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Resume'),
        ),
        migrations.AddField(
            model_name='interview',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Vendor'),
        ),
    ]
