# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='fname',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='lname',
        ),
    ]
