# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobDetails'),
        ),
    ]
