# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190121_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobrole',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobcreatedate',
            field=models.DateField(default=datetime.date(2019, 2, 28)),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaddate',
            field=models.DateField(default=datetime.date(2019, 2, 28)),
        ),
    ]
