# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190112_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=200)),
                ('positionname', models.CharField(max_length=200)),
                ('jobstatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=200)),
                ('positionname', models.CharField(max_length=200)),
                ('resourcename', models.CharField(max_length=200)),
                ('uploaddate', models.DateField()),
                ('profilestatus', models.CharField(max_length=200)),
            ],
        ),
    ]
