# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdetails_profiledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='assignedto',
            field=models.CharField(default='test1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='resourcemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='clientname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='positionname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='clientname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='positionname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='resourcename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='emailid',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
