# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190228_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='designation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='picfile',
            field=models.ImageField(default='hello', upload_to=b'documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobcreatedate',
            field=models.DateField(default=datetime.date(2019, 3, 5)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaddate',
            field=models.DateField(default=datetime.date(2019, 3, 5)),
        ),
    ]
