# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190112_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='uname',
        ),
    ]
