# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-10 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190305_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='clientrate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='contracttype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='visapreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='availability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='billrate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='visastatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobcreatedate',
            field=models.DateField(default=datetime.date(2019, 3, 10)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaddate',
            field=models.DateField(default=datetime.date(2019, 3, 10)),
        ),
    ]
