# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190112_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='profilestatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
