# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190112_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='submittedby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
