# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-14 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20190113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobcreatedate',
            field=models.DateField(default=datetime.date(2019, 1, 14)),
        ),
    ]
